import Head from "next/head";
import { Text } from "@nextui-org/react";

//COMPONENTS
import Glow from "@/components/Glow";
import SiteNavbar from "@/components/Navbar";
import Projects from "@/components/Projects";
import ContactUsButton from "@/components/ContactUsButton";

import BouncingBlob from "@/components/BouncingBlob";

export default function Home() {
  return (
    <>
      <Head>
        <title>AURORA studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Glow />
      <div id="blur"></div>
      <BouncingBlob
        canWidth={1920}
        canHeight={1080}
        blobWidth={800}
        blobHeight={800}
        color="pink"
      />

      <BouncingBlob
        canWidth={1920}
        canHeight={1080}
        blobWidth={600}
        blobHeight={600}
        color="blue"
      />

      <BouncingBlob
        canWidth={1920}
        canHeight={1080}
        blobWidth={400}
        blobHeight={400}
        color="purple"
      />

      <SiteNavbar />
      <ContactUsButton />

      <main className="main">
        <div className="header">
          <div className="subtitle">
            <Text
              size={80}
              css={{
                lineHeight: "1em",
              }}
              weight="bold"
            >
              Baví nás řešit digitální problémy za použití kreativity a
              nekonvenčního myšlení!
            </Text>
          </div>
        </div>

        {/* <div className="about section"></div> */}

        <div className="works section">
          <Text h2>Naše projekty</Text>
          <Projects />
        </div>
      </main>
    </>
  );
}
