import Head from "next/head";
import { Text } from "@nextui-org/react";

//COMPONENTS
import Glow from "@/components/Glow";
import SiteNavbar from "@/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Glow />
      <div id="blur"></div>

      <SiteNavbar />
      <main className="main">
        <div className="header">
          <div className="subtitle">
            <Text
              size={80}
              css={{
                lineHeight: "1em",
              }}
              weight="bold"
            >
              Baví nás řešit digitální problémy za použití kreativity a
              nekonvenčního myšlení!
            </Text>
          </div>
        </div>

        <div className="works section">
          <Text h2>Naše projekty</Text>
        </div>
      </main>
    </>
  );
}
